# yaml-language-server: $schema=https://raw.githubusercontent.com/binary-install/binstaller/main/schema/InstallSpec.json
schema: v1
repo: direnv/direnv
default_version: v2.37.1 # renovate: datasource=github-releases depName=direnv/direnv
asset:
  template: direnv.${OS}-${ARCH}${EXT}
checksum:
