# yaml-language-server: $schema=https://raw.githubusercontent.com/binary-install/binstaller/main/schema/InstallSpec.json
schema: v1
repo: ekalinin/github-markdown-toc.go
default_version: v2.0.1 # renovate: datasource=github-releases depName=ekalinin/github-markdown-toc.go
asset:
  template: gh-md-toc_${VERSION}_${OS}_${ARCH}${EXT}
  default_extension: .tar.gz
  binaries:
    - name: gh-md-toc
      path: gh-md-toc
checksums:
  algorithm: sha256
  template: checksums.txt
  embedded_checksums:
    v2.0.0:
    - filename: gh-md-toc_2.0.0_darwin_amd64.tar.gz
      hash: 622626f7880f6b604e93c06638e948500f4b458703d4066e91bae5b857934666
    - filename: gh-md-toc_2.0.0_darwin_arm64.tar.gz
      hash: 6a610cfe0e30e46ba49027da8eef3869fd2b98be9403b9d231df8c619bb59659
    - filename: gh-md-toc_2.0.0_linux_amd64.tar.gz
      hash: 7546a6e1146ba53d23a657cd6e93f2ed6ed0cc06bcf882c8f2983116f758adf5
    - filename: gh-md-toc_2.0.0_linux_arm64.tar.gz
      hash: 30487683256f1a0a923433b97730b74110552e857506e3fee5cc2d11ee7366ed
    - filename: gh-md-toc_2.0.0_linux_armv6.tar.gz
      hash: c715d4432e95dda4a06232c9b3c01e945e07ec00a11355b5f1d4804f36794bcb
    - filename: gh-md-toc_2.0.0_windows_amd64.tar.gz
      hash: d06b047b3314c875034f8e29f07a1c8498e3bfaab3b01cbfa06f7d37e013d222
    - filename: gh-md-toc_2.0.0_windows_arm64.tar.gz
      hash: 22d045c736b3fedc90e42467c92dbb43bef3d8a625f05587070f6ca0b2d4f1d1
    - filename: gh-md-toc_2.0.0_windows_armv6.tar.gz
      hash: 24c85ede2c0d897993174d5df9905ee6d9f78d95a0f5d36a1324ab55e0dac735
