# yaml-language-server: $schema=https://raw.githubusercontent.com/binary-install/binstaller/main/schema/InstallSpec.json
schema: v1
repo: aaif-goose/goose
default_version: v1.41.0 # renovate: datasource=github-releases depName=aaif-goose/goose
asset:
  template: goose-${ARCH}-${OS}${EXT}
  default_extension: .tar.bz2
  rules:
  - when:
      arch: amd64
    arch: x86_64
  - when:
      arch: arm64
    arch: aarch64
  - when:
      os: darwin
    os: apple-darwin
  - when:
      os: linux
    os: unknown-linux-musl
  - when:
      os: windows
    os: pc-windows-msvc
  - when:
      os: windows
    template: goose-${ARCH}-${OS}-cuda${EXT}
    ext: .zip
checksums:
  algorithm: sha256
  embedded_checksums:
    v1.41.0:
    - filename: goose-aarch64-apple-darwin.tar.bz2
      hash: 84e145273dc5b6100c392cc765376ee75d1bf37a2ef9e9fd9c42fee0d2d997e8
    - filename: goose-aarch64-unknown-linux-musl.tar.bz2
      hash: 7021b0c57f17abc9fe2c7e66e3e0c75b968a61b8d5796c6579f8e62aeacacdf3
    - filename: goose-x86_64-apple-darwin.tar.bz2
      hash: b039fe30eecc54e85c7dca247cd96ed3064fa123551595e07b9f83b0cb7e8c15
    - filename: goose-x86_64-pc-windows-msvc-cuda.zip
      hash: be07cdd60cf2f13e154a0667386f8979369d81c705af9c27cfcf79d42365dd67
    - filename: goose-x86_64-unknown-linux-musl.tar.bz2
      hash: 7f34060691a35a11c733cf771a9c572b73716e94d5ad9e57c97922d727b8527f
