# yaml-language-server: $schema=https://raw.githubusercontent.com/binary-install/binstaller/main/schema/InstallSpec.json
schema: v1
repo: jdx/mise
default_version: v2026.4.17  # renovate: datasource=github-releases depName=jdx/mise
asset:
  template: mise-${TAG}-${OS}-${ARCH}-musl${EXT}
  default_extension: .tar.gz
  binaries:
    - name: mise
      path: mise/bin/mise
  rules:
  - when:
      arch: amd64
    arch: x64
  - when:
      os: darwin
    os: macos
  - when:
      os: darwin
    template: mise-${TAG}-${OS}-${ARCH}${EXT}
  - when:
      os: windows
    template: mise-${TAG}-${OS}-${ARCH}${EXT}
    ext: .zip
checksums:
  algorithm: sha256
  template: SHASUMS256.txt
  embedded_checksums:
    v2026.4.17: []
