# yaml-language-server: $schema=https://raw.githubusercontent.com/binary-install/binstaller/main/schema/InstallSpec.json
schema: v1
repo: tofuutils/tenv
default_version: v4.10.1 # renovate: datasource=github-releases depName=tofuutils/tenv
asset:
  template: tenv_${TAG}_${OS}_${ARCH}${EXT}
  default_extension: .tar.gz
  binaries:
    - name: atmos
      path: atmos
    - name: tenv
      path: tenv
    - name: terraform
      path: terraform
    - name: terragrunt
      path: terragrunt
    - name: terramate
      path: terramate
    - name: tf
      path: tf
    - name: tofu
      path: tofu
  rules:
  - when:
      arch: amd64
    arch: x86_64
  - when:
      os: darwin
    os: Darwin
  - when:
      os: linux
    os: Linux
  - when:
      os: windows
    os: Windows
  - when:
      os: windows
    ext: .zip
checksums:
  algorithm: sha256
  template: tenv_${TAG}_checksums.txt
  embedded_checksums:
    v4.10.1:
    - filename: tenv_v4.10.1_Darwin_arm64.tar.gz
      hash: f71f0137c4fac4e9b99621fd9a7a3c2204ec1f421d16d75c93383eb14962574e
    - filename: tenv_v4.10.1_Darwin_x86_64.tar.gz
      hash: d5ab28ae9f264e47aea1b50391de693b4dad3ed74858f9152471c711a97fabfe
    - filename: tenv_v4.10.1_Linux_arm64.tar.gz
      hash: 75c2d3bc7756328a96c75e1d1c269356d66ab5380a69b73b81aa17bceb40b772
    - filename: tenv_v4.10.1_Linux_armv6.tar.gz
      hash: 51fcefab715631cc59dd08ab92910e11ce468b27227f661fb19f11486d7533af
    - filename: tenv_v4.10.1_Linux_x86_64.tar.gz
      hash: 8c45d8d52a3f0469f9231d4d38e14acc753d608898b38765d728553dd2d9f7ed
    - filename: tenv_v4.10.1_Windows_arm64.zip
      hash: cde51c5246518bc7a685b272b020184fdb6dce1df7a783da3c2f7abc7527ce59
    - filename: tenv_v4.10.1_Windows_x86_64.zip
      hash: 255431703c8655c7c52a92251c512619e0d2f90677ae514cfe642a568ac6d2ff
