# yaml-language-server: $schema=https://raw.githubusercontent.com/binary-install/binstaller/main/schema/InstallSpec.json
schema: v1
repo: aquasecurity/trivy
asset:
  template: trivy_${VERSION}_${OS}-${ARCH}${EXT}
  default_extension: .tar.gz
  rules:
  - when:
      arch: amd64
    arch: 64bit
  - when:
      arch: arm64
    arch: ARM64
  - when:
      os: darwin
    os: macOS
  - when:
      os: linux
    os: Linux
  - when:
      os: windows
    ext: .zip
checksums:
  algorithm: sha256
  template: trivy_${VERSION}_checksums.txt
  embedded_checksums:
    v0.70.0: # renovate: datasource=github-releases depName=aquasecurity/trivy
    - filename: trivy_0.68.2_Linux-64bit.tar.gz
      hash: 3d933bbc3685f95ec15280f620583d05d97ee3affb66944d14481d5d6d567064
    - filename: trivy_0.68.2_Linux-ARM64.tar.gz
      hash: 33c87995fd0c3d1559086c3e18fd3148051296dfd0ca2a67583eb64f89998c91
    - filename: trivy_0.68.2_Linux-s390x.tar.gz
      hash: fd45fc808622ecb11393f4c27d1fbd20e1d78838148a282b1129624964dd0628
    - filename: trivy_0.68.2_macOS-64bit.tar.gz
      hash: c0790530cd717b6bdd02ed437be0710f5c7043078fafaf6841be7c865bf251ce
    - filename: trivy_0.68.2_macOS-ARM64.tar.gz
      hash: dfbe15ffe47426dad9fd3e0d52aeacf3dbbb25ca5dbc66049f5920834435988d
    - filename: trivy_0.68.2_windows-64bit.zip
      hash: 2aaa0ce06f9f2221a6bb21e1fc0e0ecc6aeb56362bc5c9463e9fd7b06983c3c3
