# yaml-language-server: $schema=https://raw.githubusercontent.com/binary-install/binstaller/main/schema/InstallSpec.json
schema: v1
repo: aquasecurity/trivy
asset:
  template: trivy_${VERSION}_${OS}-${ARCH}${EXT}
  default_extension: .tar.gz
  rules:
  - when:
      arch: amd64
    arch: 64bit
  - when:
      arch: arm64
    arch: ARM64
  - when:
      os: darwin
    os: macOS
  - when:
      os: linux
    os: Linux
  - when:
      os: windows
    ext: .zip
checksums:
  algorithm: sha256
  template: trivy_${VERSION}_checksums.txt
  embedded_checksums:
    v0.70.0: # renovate: datasource=github-releases depName=aquasecurity/trivy
    - filename: trivy_0.70.0_Linux-64bit.tar.gz
      hash: 8b4376d5d6befe5c24d503f10ff136d9e0c49f9127a4279fd110b727929a5aa9
    - filename: trivy_0.70.0_Linux-ARM64.tar.gz
      hash: 2f6bb988b553a1bbac6bdd1ce890f5e412439564e17522b88a4541b4f364fc8d
    - filename: trivy_0.70.0_Linux-s390x.tar.gz
      hash: 92ec9caffdcc32d43b76d21d4ecd6ea2975a2b37e050d5f79e17651c490b1753
    - filename: trivy_0.70.0_macOS-64bit.tar.gz
      hash: 52d531452b19e7593da29366007d02a810e1e0080d02f9cf6a1afb46c35aaa93
    - filename: trivy_0.70.0_macOS-ARM64.tar.gz
      hash: 68e543c51dcc96e1c344053a4fde9660cf602c25565d9f09dc17dd41e13b838a
    - filename: trivy_0.70.0_windows-64bit.zip
      hash: eea5442eab86f9e26cd718d7618d43899e72a83767619e8bee47911bddbfb825
