# yaml-language-server: $schema=https://raw.githubusercontent.com/binary-install/binstaller/main/schema/InstallSpec.json
schema: v1
repo: trufflesecurity/trufflehog
asset:
  template: trufflehog_${VERSION}_${OS}_${ARCH}${EXT}
  default_extension: .tar.gz
checksums:
  algorithm: sha256
  template: trufflehog_${VERSION}_checksums.txt
  embedded_checksums:
    v3.94.3: # renovate: datasource=github-releases depName=trufflesecurity/trufflehog
    - filename: trufflehog_3.94.3_darwin_amd64.tar.gz
      hash: afea2e94a1bb274bdad1758aadd6f033f875dd4c1c06cbcdc47076ed91cc62e5
    - filename: trufflehog_3.94.3_darwin_arm64.tar.gz
      hash: f2dca2e62f02027ef3f164068ec2632230764a816a336efe15e0facb70fe8731
    - filename: trufflehog_3.94.3_linux_amd64.tar.gz
      hash: 7cc45010bfac7258a23731bc3ab4371abdbf20ffc705075066971e5aa8ebda7f
    - filename: trufflehog_3.94.3_linux_arm64.tar.gz
      hash: 57699423c593b63d5baa690ca4105f13b61c80480177160c6fc4b31cbac3af56
    - filename: trufflehog_3.94.3_windows_amd64.tar.gz
      hash: 6b8da3097cbeaded6d97d30d76c3ff7a54e94a256d3189e09deb9f715381d8da
    - filename: trufflehog_3.94.3_windows_arm64.tar.gz
      hash: 8e730e35ad013a08612691212af44e333b1fdba694193a02521cca82065244ab
