# yaml-language-server: $schema=https://raw.githubusercontent.com/binary-install/binstaller/main/schema/InstallSpec.json
schema: v1
repo: trufflesecurity/trufflehog
asset:
  template: trufflehog_${VERSION}_${OS}_${ARCH}${EXT}
  default_extension: .tar.gz
checksums:
  algorithm: sha256
  template: trufflehog_${VERSION}_checksums.txt
  embedded_checksums:
    v3.92.4: # renovate: datasource=github-releases depName=trufflesecurity/trufflehog
    - filename: trufflehog_3.92.4_darwin_amd64.tar.gz
      hash: 7599e25b2d9c8eea30aac873114bad54cb254a3dbc4b01cac52b28ef9f013f0e
    - filename: trufflehog_3.92.4_darwin_arm64.tar.gz
      hash: 37df43ad0cda48931c4586fe78064d1dd33016c8253ec27339c735fc956264f8
    - filename: trufflehog_3.92.4_linux_amd64.tar.gz
      hash: 98937dbfe048695bf1f34e8b76e6ef4caf75260760c0b5777dddf9bf34803052
    - filename: trufflehog_3.92.4_linux_arm64.tar.gz
      hash: 85868c235ed8871e87191c252c3b8cb6b7da6942aba210f048848a583b964fa4
    - filename: trufflehog_3.92.4_windows_amd64.tar.gz
      hash: 39357653008d4af2245e3e1c02e118a9dc80b203284f25f9a2b11a573d418938
    - filename: trufflehog_3.92.4_windows_arm64.tar.gz
      hash: 613d4d0fd180e9f5be21568150e7a71cad0cfe53b71ef1fac970a68a5a06e411
