#!/bin/sh
# aws-cli-install.sh — thin wrapper around AWS's official AWS CLI v2 installer.
#
# This script is NOT generated by binstaller. The AWS CLI is not distributed via
# GitHub releases (it is hosted on https://awscli.amazonaws.com), so binstaller
# cannot generate a script for it in its current form. See
# `Plan-aws-alternative.md` for a plan that replaces this wrapper with a
# binstaller-equivalent script that verifies checksums and installs the
# `aws` binary directly, matching the shape of the other scripts in this repo.
#
# What this script does:
#   1. Detects OS/arch (Linux x86_64 / aarch64 only — macOS uses a .pkg and is
#      out of scope for a user-mode installer; install via Homebrew on macOS).
#   2. Downloads the AWS-published zip bundle from awscli.amazonaws.com.
#   3. Unpacks it and runs the vendor-supplied `./aws/install` script, which
#      lays down a versioned install tree and creates `aws` + `aws_completer`
#      symlinks in the requested bindir.
#
# Defaults are chosen for user-mode (no sudo) install in a devcontainer:
#   install dir (-i):  ${HOME}/.local/aws-cli
#   bin dir     (-b):  ${HOME}/.local/bin
#
# This is a deliberate thin wrapper: no checksum verification beyond what
# AWS's installer does internally, no pinning of the installer script itself,
# no GPG signature check. Use Plan-aws-alternative.md for a hardened path.

set -eu

SCRIPT_NAME=$(basename "$0")

usage() {
  cat <<EOF
${SCRIPT_NAME}: install the AWS CLI v2 via AWS's official installer.

Usage: ${SCRIPT_NAME} [-b bindir] [-i installdir] [-d] [-q] [-n] [version]
  -b   bindir where 'aws' / 'aws_completer' symlinks are created
       (default: \${HOME}/.local/bin)
  -i   installdir where the versioned AWS CLI tree is laid down
       (default: \${HOME}/.local/aws-cli)
  -d   debug logging
  -q   quiet mode (errors only)
  -n   dry run — print what would happen, do nothing
  [version]  Optional specific version, e.g. 2.17.42.
             If omitted, installs the latest published by AWS.

Supported platforms: linux/amd64, linux/arm64.
On macOS, install via Homebrew: 'brew install awscli'.

See also: Plan-aws-alternative.md (a binstaller-style replacement with
pinned versions + checksum verification).
EOF
  exit 2
}

# --- logging ---------------------------------------------------------------
_quiet=0
_debug=0
log_debug() { [ "${_debug}" -eq 1 ] && echo "[debug] $*" 1>&2 || :; }
log_info()  { [ "${_quiet}" -eq 0 ] && echo "[info]  $*" 1>&2 || :; }
log_err()   { echo "[err]   $*" 1>&2; }

# --- flags -----------------------------------------------------------------
BINDIR="${HOME}/.local/bin"
INSTALLDIR="${HOME}/.local/aws-cli"
DRY_RUN=0

while getopts "b:i:dqnh?" opt; do
  case "${opt}" in
    b) BINDIR="${OPTARG}" ;;
    i) INSTALLDIR="${OPTARG}" ;;
    d) _debug=1 ;;
    q) _quiet=1 ;;
    n) DRY_RUN=1 ;;
    h|\?) usage ;;
  esac
done
shift $((OPTIND - 1))

VERSION="${1:-}"

# --- platform detection ----------------------------------------------------
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
MACHINE=$(uname -m)

case "${OS}" in
  linux) ;;
  darwin)
    log_err "macOS is not supported by this script. Install via Homebrew: 'brew install awscli'."
    exit 1
    ;;
  *)
    log_err "unsupported OS: ${OS}"
    exit 1
    ;;
esac

case "${MACHINE}" in
  x86_64|amd64)  AWS_ARCH="x86_64" ;;
  aarch64|arm64) AWS_ARCH="aarch64" ;;
  *)
    log_err "unsupported architecture: ${MACHINE}"
    exit 1
    ;;
esac

# --- URL construction ------------------------------------------------------
# AWS publishes:
#   https://awscli.amazonaws.com/awscli-exe-linux-${ARCH}.zip           (latest)
#   https://awscli.amazonaws.com/awscli-exe-linux-${ARCH}-${VERSION}.zip (pinned)
BASE_URL="https://awscli.amazonaws.com"
if [ -n "${VERSION}" ]; then
  ASSET="awscli-exe-linux-${AWS_ARCH}-${VERSION}.zip"
else
  ASSET="awscli-exe-linux-${AWS_ARCH}.zip"
fi
URL="${BASE_URL}/${ASSET}"

log_info "AWS CLI install plan:"
log_info "  url        : ${URL}"
log_info "  bindir     : ${BINDIR}"
log_info "  installdir : ${INSTALLDIR}"
log_info "  version    : ${VERSION:-latest}"

if [ "${DRY_RUN}" -eq 1 ]; then
  log_info "dry run — exiting before download."
  exit 0
fi

# --- prerequisites ---------------------------------------------------------
for bin in curl unzip; do
  if ! command -v "${bin}" >/dev/null 2>&1; then
    log_err "required command '${bin}' not found in PATH."
    exit 1
  fi
done

mkdir -p "${BINDIR}" "${INSTALLDIR}"

# --- download + unpack + install ------------------------------------------
TMPDIR=$(mktemp -d)
trap 'rm -rf "${TMPDIR}"' EXIT HUP INT TERM

log_info "downloading ${URL}"
curl --fail --location --show-error ${_quiet:+--silent} \
     --output "${TMPDIR}/awscliv2.zip" "${URL}"

log_info "unpacking"
( cd "${TMPDIR}" && unzip ${_quiet:+-q} -o awscliv2.zip )

# AWS's installer script:
#   -i <installdir>  versioned tree root (will contain v2/<version>/...)
#   -b <bindir>      where to create `aws` and `aws_completer` symlinks
#   --update         allow upgrading an existing install in-place
UPDATE_FLAG=""
if [ -x "${BINDIR}/aws" ] || [ -d "${INSTALLDIR}/v2" ]; then
  UPDATE_FLAG="--update"
  log_info "existing install detected — running with --update"
fi

log_info "running AWS installer"
"${TMPDIR}/aws/install" -i "${INSTALLDIR}" -b "${BINDIR}" ${UPDATE_FLAG}

log_info "installed: $(${BINDIR}/aws --version 2>&1)"
