#!/bin/sh
# aws-cli-install.sh — thin wrapper around AWS's official AWS CLI v2 installer.
#
# This script is NOT generated by binstaller. The AWS CLI is not distributed via
# GitHub releases (it is hosted on https://awscli.amazonaws.com), so binstaller
# cannot generate a script for it in its current form. See
# `Plan-aws-alternative.md` for a plan that replaces this wrapper with a
# binstaller-equivalent script that verifies checksums and installs the
# `aws` binary directly, matching the shape of the other scripts in this repo.
#
# What this script does:
#   1. Detects OS/arch (Linux x86_64 / aarch64 only — macOS uses a .pkg and is
#      out of scope for a user-mode installer; install via Homebrew on macOS).
#   2. Downloads the AWS-published zip bundle from awscli.amazonaws.com.
#   3. Unpacks it and runs the vendor-supplied `./aws/install` script, which
#      lays down a versioned install tree and creates `aws` + `aws_completer`
#      symlinks in the requested bindir.
#
# Defaults are chosen for user-mode (no sudo) install in a devcontainer:
#   install dir (-i):  ${HOME}/.local/aws-cli
#   bin dir     (-b):  ${HOME}/.local/bin
#
# This is a deliberate thin wrapper: no checksum verification beyond what
# AWS's installer does internally, no pinning of the installer script itself,
# no GPG signature check. Use Plan-aws-alternative.md for a hardened path.

set -eu

SCRIPT_NAME=$(basename "$0")

usage() {
  cat <<EOF
${SCRIPT_NAME}: install the AWS CLI v2 via AWS's official installer.

Usage: ${SCRIPT_NAME} [-b bindir] [-i installdir] [-d] [-q] [-n] [version]
  -b   bindir where 'aws' / 'aws_completer' symlinks are created
       (default: \${HOME}/.local/bin)
  -i   installdir where the versioned AWS CLI tree is laid down
       (default: \${HOME}/.local/aws-cli)
  -d   debug logging
  -q   quiet mode (errors only)
  -n   dry run — print what would happen, do nothing
  [version]  Optional specific version, e.g. 2.17.42.
             If omitted, installs the latest published by AWS.

Supported platforms: linux/amd64, linux/arm64.
On macOS, install via Homebrew: 'brew install awscli'.

See also: Plan-aws-alternative.md (a binstaller-style replacement with
pinned versions + checksum verification).
EOF
  exit 2
}

# --- logging ---------------------------------------------------------------
_quiet=0
_debug=0
log_debug() { [ "${_debug}" -eq 1 ] && echo "[debug] $*" 1>&2 || :; }
log_info()  { [ "${_quiet}" -eq 0 ] && echo "[info]  $*" 1>&2 || :; }
log_err()   { echo "[err]   $*" 1>&2; }

# --- flags -----------------------------------------------------------------
BINDIR="${HOME}/.local/bin"
INSTALLDIR="${HOME}/.local/aws-cli"
DRY_RUN=0

while getopts "b:i:dqnh?" opt; do
  case "${opt}" in
    b) BINDIR="${OPTARG}" ;;
    i) INSTALLDIR="${OPTARG}" ;;
    d) _debug=1 ;;
    q) _quiet=1 ;;
    n) DRY_RUN=1 ;;
    h|\?) usage ;;
  esac
done
shift $((OPTIND - 1))

VERSION="${1:-}"

# --- platform detection ----------------------------------------------------
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
MACHINE=$(uname -m)

case "${OS}" in
  linux) ;;
  darwin)
    log_err "macOS is not supported by this script. Install via Homebrew: 'brew install awscli'."
    exit 1
    ;;
  *)
    log_err "unsupported OS: ${OS}"
    exit 1
    ;;
esac

# AWS does not publish a musl build of AWS CLI v2 — the bundled `aws` binary
# is glibc-linked and will fail with "required file not found" on Alpine and
# other musl distros (see https://github.com/aws/aws-cli/issues/4685).
# Detect musl early and refuse rather than leaving a broken install behind.
detect_libc() {
  # Prefer a direct check for the musl dynamic linker.
  for f in /lib/ld-musl-aarch64.so.1 /lib/ld-musl-x86_64.so.1 /lib/ld-musl-armhf.so.1; do
    [ -e "$f" ] && { echo musl; return; }
  done
  # Fallback: ask ldd.
  if ldd --version 2>&1 | grep -qi musl; then
    echo musl
    return
  fi
  echo glibc
}

LIBC=$(detect_libc)
if [ "${LIBC}" = "musl" ]; then
  log_err "AWS CLI v2 is not supported on musl libc (Alpine, etc.)."
  log_err "AWS only ships a glibc-linked bundle; running it on musl fails with"
  log_err "  'required file not found' (missing ELF interpreter)."
  log_err "Workarounds:"
  log_err "  * run inside a glibc-based container (debian/ubuntu/amazonlinux)"
  log_err "  * use the 'aws-cli' Alpine community package: 'apk add aws-cli'"
  log_err "  * install 'gcompat' and retry (unsupported by AWS)"
  exit 1
fi

# AWS CLI v2 is glibc-linked; musl-based systems (Alpine, etc.) cannot run it.
if ldd --version 2>&1 | grep -qi musl; then
  log_err "AWS CLI requires glibc but this system uses musl libc."
  log_err "On Alpine: 'apk add aws-cli'. On Debian/Ubuntu-based images: use a glibc image."
  exit 1
fi

case "${MACHINE}" in
  x86_64|amd64)  AWS_ARCH="x86_64" ;;
  aarch64|arm64) AWS_ARCH="aarch64" ;;
  *)
    log_err "unsupported architecture: ${MACHINE}"
    exit 1
    ;;
esac

# --- URL construction ------------------------------------------------------
# AWS publishes:
#   https://awscli.amazonaws.com/awscli-exe-linux-${ARCH}.zip           (latest)
#   https://awscli.amazonaws.com/awscli-exe-linux-${ARCH}-${VERSION}.zip (pinned)
BASE_URL="https://awscli.amazonaws.com"
if [ -n "${VERSION}" ]; then
  ASSET="awscli-exe-linux-${AWS_ARCH}-${VERSION}.zip"
else
  ASSET="awscli-exe-linux-${AWS_ARCH}.zip"
fi
URL="${BASE_URL}/${ASSET}"

log_info "AWS CLI install plan:"
log_info "  url        : ${URL}"
log_info "  bindir     : ${BINDIR}"
log_info "  installdir : ${INSTALLDIR}"
log_info "  version    : ${VERSION:-latest}"

if [ "${DRY_RUN}" -eq 1 ]; then
  log_info "dry run — exiting before download."
  exit 0
fi

# --- prerequisites ---------------------------------------------------------
for bin in curl unzip; do
  if ! command -v "${bin}" >/dev/null 2>&1; then
    log_err "required command '${bin}' not found in PATH."
    exit 1
  fi
done

mkdir -p "${BINDIR}" "${INSTALLDIR}"

# --- download + unpack + install ------------------------------------------
TMPDIR=$(mktemp -d)
trap 'rm -rf "${TMPDIR}"' EXIT HUP INT TERM

log_info "downloading ${URL}"
curl --fail --location --show-error ${_quiet:+--silent} \
     --output "${TMPDIR}/awscliv2.zip" "${URL}"

log_info "unpacking"
( cd "${TMPDIR}" && unzip ${_quiet:+-q} -o awscliv2.zip )

# AWS's installer script:
#   -i <installdir>  versioned tree root (will contain v2/<version>/...)
#   -b <bindir>      where to create `aws` and `aws_completer` symlinks
#   --update         allow upgrading an existing install in-place
UPDATE_FLAG=""
if [ -x "${BINDIR}/aws" ] || [ -d "${INSTALLDIR}/v2" ]; then
  UPDATE_FLAG="--update"
  log_info "existing install detected — running with --update"
fi

log_info "running AWS installer"
"${TMPDIR}/aws/install" -i "${INSTALLDIR}" -b "${BINDIR}" ${UPDATE_FLAG}

# The AWS installer prints 'You can now run: ...' before it has verified the
# binary is actually executable on this host. Verify ourselves and fail loudly
# so a broken install does not look successful.
if ! "${BINDIR}/aws" --version >/tmp/aws-cli-install.$$ 2>&1; then
  log_err "post-install verification failed — '${BINDIR}/aws --version' did not run cleanly:"
  sed 's/^/  /' /tmp/aws-cli-install.$$ 1>&2 || :
  rm -f /tmp/aws-cli-install.$$
  log_err "the binary was copied but cannot execute on this host (libc / arch mismatch?)."
  exit 1
fi
log_info "installed: $(cat /tmp/aws-cli-install.$$)"
rm -f /tmp/aws-cli-install.$$
