#!/bin/sh
# gcloud-install.sh — installer for the Google Cloud CLI (gcloud).
#
# This script is NOT generated by binstaller. The Google Cloud CLI is not
# distributed via GitHub releases (it is hosted on dl.google.com), so
# binstaller cannot generate a script for it.
#
# What this script does:
#   1. Detects OS/arch (linux/darwin, x86_64/arm/x86).
#   2. Downloads the Google Cloud CLI tarball from dl.google.com.
#   3. Extracts the tarball and runs the vendor-supplied install.sh script,
#      which lays down the SDK tree and optionally updates PATH / completions.
#
# Defaults are chosen for user-mode (no sudo) install:
#   install dir (-i):  ${HOME}/.local/google-cloud-sdk
#   bin dir     (-b):  ${HOME}/.local/bin
#
# The vendor install.sh places everything under google-cloud-sdk/. This script
# extracts it into the install dir and symlinks key binaries (gcloud, gsutil,
# bq) into bindir.

set -eu

SCRIPT_NAME=$(basename "$0")

usage() {
  cat <<EOF
${SCRIPT_NAME}: install the Google Cloud CLI (gcloud).

Usage: ${SCRIPT_NAME} [-b bindir] [-i installdir] [-d] [-q] [-n]
  -b   bindir where 'gcloud', 'gsutil', 'bq' symlinks are created
       (default: \${HOME}/.local/bin)
  -i   installdir where the google-cloud-sdk tree is placed
       (default: \${HOME}/.local/google-cloud-sdk)
  -d   debug logging
  -q   quiet mode (errors only)
  -n   dry run — print what would happen, do nothing

Supported platforms: linux/x86_64, linux/arm, linux/x86,
                     darwin/x86_64, darwin/arm64.
EOF
  exit 2
}

# --- logging ---------------------------------------------------------------
_quiet=0
_debug=0
log_debug() { [ "${_debug}" -eq 1 ] && echo "[debug] $*" 1>&2 || :; }
log_info()  { [ "${_quiet}" -eq 0 ] && echo "[info]  $*" 1>&2 || :; }
log_err()   { echo "[err]   $*" 1>&2; }

# --- flags -----------------------------------------------------------------
BINDIR="${HOME}/.local/bin"
INSTALLDIR="${HOME}/.local/google-cloud-sdk"
DRY_RUN=0

while getopts "b:i:dqnh?" opt; do
  case "${opt}" in
    b) BINDIR="${OPTARG}" ;;
    i) INSTALLDIR="${OPTARG}" ;;
    d) _debug=1 ;;
    q) _quiet=1 ;;
    n) DRY_RUN=1 ;;
    h|\?) usage ;;
  esac
done
shift $((OPTIND - 1))

# --- platform detection ----------------------------------------------------
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
MACHINE=$(uname -m)

case "${OS}" in
  linux|darwin) ;;
  *)
    log_err "unsupported OS: ${OS}"
    exit 1
    ;;
esac

case "${MACHINE}" in
  x86_64|amd64)    GCLOUD_ARCH="x86_64" ;;
  aarch64|arm64)   GCLOUD_ARCH="arm" ;;
  i386|i686)       GCLOUD_ARCH="x86" ;;
  *)
    log_err "unsupported architecture: ${MACHINE}"
    exit 1
    ;;
esac

# --- URL construction ------------------------------------------------------
BASE_URL="https://dl.google.com/dl/cloudsdk/channels/rapid/downloads"
ASSET="google-cloud-cli-${OS}-${GCLOUD_ARCH}.tar.gz"
URL="${BASE_URL}/${ASSET}"

log_info "Google Cloud CLI install plan:"
log_info "  url        : ${URL}"
log_info "  bindir     : ${BINDIR}"
log_info "  installdir : ${INSTALLDIR}"
if [ "${DRY_RUN}" -eq 1 ]; then
  log_info "dry run — exiting before download."
  exit 0
fi

# --- prerequisites ---------------------------------------------------------
for bin in curl tar python; do
  if ! command -v "${bin}" >/dev/null 2>&1; then
    log_err "required command '${bin}' not found in PATH."
    exit 1
  fi
done

mkdir -p "${BINDIR}"

# --- download + extract + install ------------------------------------------
TMPDIR=$(mktemp -d)
trap 'rm -rf "${TMPDIR}"' EXIT HUP INT TERM

TARBALL="${TMPDIR}/${ASSET}"

log_info "downloading ${URL}"
curl --fail --location --show-error ${_quiet:+--silent} \
     --output "${TARBALL}" "${URL}"

# If there is an existing install, remove it so we get a clean extraction.
if [ -d "${INSTALLDIR}" ]; then
  log_info "removing existing install at ${INSTALLDIR}"
  rm -rf "${INSTALLDIR}"
fi

# The tarball extracts to google-cloud-sdk/. We extract to a temp location
# then move it to the final install dir.
log_info "extracting"
tar -xf "${TARBALL}" -C "${TMPDIR}"

# Move extracted tree to the install location.
mkdir -p "$(dirname "${INSTALLDIR}")"
mv "${TMPDIR}/google-cloud-sdk" "${INSTALLDIR}"

# Run the vendor install.sh non-interactively:
#   --quiet                  suppress prompts
#   --usage-reporting false  opt out of usage reporting
#   --path-update false      we manage PATH ourselves via symlinks
#   --command-completion false
log_info "running vendor install.sh"
"${INSTALLDIR}/install.sh" \
  --quiet \
  --usage-reporting false \
  --path-update false \
  --command-completion false

# --- create symlinks -------------------------------------------------------
for cmd in gcloud gsutil bq; do
  SRC="${INSTALLDIR}/bin/${cmd}"
  DST="${BINDIR}/${cmd}"
  if [ -e "${SRC}" ]; then
    ln -sf "${SRC}" "${DST}"
    log_debug "symlinked ${DST} -> ${SRC}"
  else
    log_debug "skipping ${cmd} — not found in SDK bin/"
  fi
done

# --- verify ----------------------------------------------------------------
if ! "${BINDIR}/gcloud" version >/tmp/gcloud-install.$$ 2>&1; then
  log_err "post-install verification failed — '${BINDIR}/gcloud version' did not run cleanly:"
  sed 's/^/  /' /tmp/gcloud-install.$$ 1>&2 || :
  rm -f /tmp/gcloud-install.$$
  exit 1
fi

INSTALLED_VERSION=$(head -1 /tmp/gcloud-install.$$)
log_info "installed: ${INSTALLED_VERSION}"
rm -f /tmp/gcloud-install.$$
log_info "binaries available in ${BINDIR}: gcloud, gsutil, bq"
