#!/bin/sh
# Code generated by binstaller. DO NOT EDIT.
#
set -e
usage() {
  this=$1
  cat <<EOF
$this: download ${NAME} from ${REPO}

Usage: $this [-b bindir] [-d] [-q] [-n] [tag]
  -b sets bindir or installation directory, Defaults to ${BINSTALLER_BIN:-${HOME}/.local/bin}
  -d turns on debug logging
  -q turns on quiet mode (errors only)
  -n turns on dry run mode
   [tag] is a tag from
   https://github.com/go-task/task/releases
   If tag is missing, then v3.50.0 will be used.

Environment variables:
  BINSTALLER_NO_PROGRESS=1   Disable progress indicators
  BINSTALLER_OS=...          Override OS detection
  BINSTALLER_ARCH=...        Override architecture detection

 Generated by binstaller
  https://github.com/binary-install/binstaller
EOF
  exit 2
}

cat /dev/null <<EOF
------------------------------------------------------------------------
https://github.com/client9/shlib - portable posix shell functions
Public domain - http://unlicense.org
https://github.com/client9/shlib/blob/master/LICENSE.md
but credit (and pull requests) appreciated.
------------------------------------------------------------------------
EOF
is_command() {
  command -v "$1" >/dev/null
}
echoerr() {
  echo "$@" 1>&2
}
_logp=6
log_set_priority() {
  _logp="$1"
}
log_priority() {
  if test -z "$1"; then
    echo "$_logp"
    return
  fi
  [ "$1" -le "$_logp" ]
}
log_tag() {
  case $1 in
    0) echo "emerg" ;;
    1) echo "alert" ;;
    2) echo "crit" ;;
    3) echo "err" ;;
    4) echo "warning" ;;
    5) echo "notice" ;;
    6) echo "info" ;;
    7) echo "debug" ;;
    *) echo "$1" ;;
  esac
}
log_debug() {
  log_priority 7 || return 0
  echoerr "$(log_prefix)" "$(log_tag 7)" "$@"
}
log_info() {
  log_priority 6 || return 0
  echoerr "$(log_prefix)" "$(log_tag 6)" "$@"
}
log_err() {
  log_priority 3 || return 0
  echoerr "$(log_prefix)" "$(log_tag 3)" "$@"
}
log_crit() {
  log_priority 2 || return 0
  echoerr "$(log_prefix)" "$(log_tag 2)" "$@"
}
uname_os() {
  os=$(uname -s | tr '[:upper:]' '[:lower:]')
  case "$os" in
    msys*) os="windows" ;;
    mingw*) os="windows" ;;
    cygwin*) os="windows" ;;
  esac
  if [ "$os" = "sunos" ]; then
    if [ "$(uname -o)" = "illumos" ]; then
      os="illumos"
    else
      os="solaris"
    fi
  fi
  echo "$os"
}
uname_arch() {
  arch=$(uname -m)
  case $arch in
    x86_64) arch="amd64" ;;
    i86pc) arch="amd64" ;;
    x86) arch="386" ;;
    i686) arch="386" ;;
    i386) arch="386" ;;
    aarch64) arch="arm64" ;;
    armv5*) arch="armv5" ;;
    armv6*) arch="armv6" ;;
    armv7*) arch="armv7" ;;
  esac
  echo "${arch}"
}
uname_os_check() {
  os=$(uname_os)
  case "$os" in
    darwin) return 0 ;;
    dragonfly) return 0 ;;
    freebsd) return 0 ;;
    linux) return 0 ;;
    android) return 0 ;;
    midnightbsd) return 0 ;;
    nacl) return 0 ;;
    netbsd) return 0 ;;
    openbsd) return 0 ;;
    plan9) return 0 ;;
    solaris) return 0 ;;
    illumos) return 0 ;;
    windows) return 0 ;;
  esac
  log_crit "uname_os_check '$(uname -s)' got converted to '$os' which is not a GOOS value. Please file bug at https://github.com/client9/shlib"
  return 1
}
uname_arch_check() {
  arch=$(uname_arch)
  case "$arch" in
    386) return 0 ;;
    amd64) return 0 ;;
    arm64) return 0 ;;
    armv5) return 0 ;;
    armv6) return 0 ;;
    armv7) return 0 ;;
    ppc64) return 0 ;;
    ppc64le) return 0 ;;
    mips) return 0 ;;
    mipsle) return 0 ;;
    mips64) return 0 ;;
    mips64le) return 0 ;;
    s390x) return 0 ;;
    amd64p32) return 0 ;;
  esac
  log_crit "uname_arch_check '$(uname -m)' got converted to '$arch' which is not a GOARCH value.  Please file bug report at https://github.com/client9/shlib"
  return 1
}
cat /dev/null <<EOF
------------------------------------------------------------------------
End of functions from https://github.com/client9/shlib
------------------------------------------------------------------------
EOF


hash_sha256() {
  TARGET=${1:-/dev/stdin}
  if is_command gsha256sum; then
    hash=$(gsha256sum "$TARGET") || return 1
    echo "$hash" | cut -d ' ' -f 1
  elif is_command sha256sum; then
    hash=$(sha256sum "$TARGET") || return 1
    echo "$hash" | cut -d ' ' -f 1
  elif is_command shasum; then
    hash=$(shasum -a 256 "$TARGET" 2>/dev/null) || return 1
    echo "$hash" | cut -d ' ' -f 1
  elif is_command openssl; then
    hash=$(openssl dgst -sha256 "$TARGET") || return 1
    echo "$hash" | cut -d ' ' -f 2
  else
    log_crit "hash_sha256 unable to find command to compute sha-256 hash"
    return 1
  fi
}

hash_compute() {
  hash_sha256 "$1"
}


# shellcheck shell=sh
# Terminal progress reporting functions
progress_init() {
  # Only show progress on interactive terminals and when not disabled
  if [ ! -t 2 ] || [ "${BINSTALLER_NO_PROGRESS}" = "1" ]; then
    return 0
  fi
  # OSC 9;4 sequences are safely ignored by unsupporting terminals
  # Only need special handling for tmux passthrough
  if [ -n "$TMUX" ]; then
    # Tmux passthrough: DCS tmux; <doubled ESC sequence> ST
    # ESC characters in the wrapped sequence must be doubled
    # Format: ESC P tmux; ESC ESC ] 9;4; ... ESC ESC \ ESC \
    PROGRESS_START=$(printf '\033Ptmux;\033\033]9;4;')
    # shellcheck disable=SC1003
    PROGRESS_END=$(printf '\033\033\\\033\\')
  else
    # Direct OSC 9;4 - terminals that don't support it will safely ignore
    PROGRESS_START=$(printf '\033]9;4;')
    PROGRESS_END=$(printf '\007')
  fi
}

# Start pulsing progress animation
progress_pulse_start() {
  # Only show progress on interactive terminals and when not disabled
  if [ ! -t 2 ] || [ "${BINSTALLER_NO_PROGRESS}" = "1" ]; then
    return 0
  fi

  # Send OSC 9;4 with state 3 (indeterminate/pulsing) once
  # The terminal will handle the continuous animation
  printf "%s3%s" "$PROGRESS_START" "$PROGRESS_END" >&2
}

# Clear progress indicator
progress_clear() {
  # Only show progress on interactive terminals and when not disabled
  if [ ! -t 2 ] || [ "${BINSTALLER_NO_PROGRESS}" = "1" ]; then
    return 0
  fi
  printf "%s0;%s" "$PROGRESS_START" "$PROGRESS_END" >&2
}

untar() {
  tarball=$1
  strip_components=${2:-0} # default 0
  case "${tarball}" in
  *.tar.gz | *.tgz) tar --no-same-owner -xzf "${tarball}" --strip-components "${strip_components}" ;;
  *.tar.xz) tar --no-same-owner -xJf "${tarball}" --strip-components "${strip_components}" ;;
  *.tar.bz2) tar --no-same-owner -xjf "${tarball}" --strip-components "${strip_components}" ;;
  *.tar) tar --no-same-owner -xf "${tarball}" --strip-components "${strip_components}" ;;
  *.gz) gunzip "${tarball}" ;;
  *.zip)
    # unzip doesn't have a standard --strip-components
    # Workaround: extract to a subdir and move contents up if stripping
    if [ "$strip_components" -gt 0 ]; then
      extract_dir=$(basename "${tarball%.zip}")_extracted
      unzip -q "${tarball}" -d "${extract_dir}"
      # Move contents of the *first* directory found inside extract_dir up
      # This assumes wrap_in_directory=true convention
      first_subdir=$(find "${extract_dir}" -mindepth 1 -maxdepth 1 -type d -print -quit)
      if [ -n "$first_subdir" ]; then
        # Move all contents (* includes hidden files)
        mv "${first_subdir}"/* .
        # Optionally remove the now-empty subdir and the extract_dir
        rmdir "${first_subdir}"
        rmdir "${extract_dir}"
      else
        log_warn "Could not find subdirectory in zip to strip components from ${extract_dir}"
        # Files are extracted in current dir anyway, proceed
      fi
    else
      unzip -q "${tarball}"
    fi
    ;;
  *)
    log_err "untar unknown archive format for ${tarball}"
    return 1
    ;;
  esac
}



hash_verify() {
  TARGET_PATH=$1
  SUMFILE=$2
  if [ -z "${SUMFILE}" ]; then
    log_err "hash_verify checksum file not specified in arg2"
    return 1
  fi
  got=$(hash_compute "$TARGET_PATH")
  if [ -z "${got}" ]; then
    log_err "failed to calculate hash: ${TARGET_PATH}"
    return 1
  fi

  BASENAME=${TARGET_PATH##*/}

  # Check for line matches in checksum file
  # Format: "<hash>  <filename>" or "<hash> *<filename>"
  # Filename may include path prefix (e.g., "deployment/m2/file.tar.gz")
  while IFS= read -r line || [ -n "$line" ]; do
    # Normalize tabs to spaces
    line=$(echo "$line" | tr '\t' ' ')

    # Remove trailing spaces for hash-only line check
    line_trimmed=$(echo "$line" | sed 's/[[:space:]]*$//')

    # Check for hash-only line (no filename) - early return
    if [ "$line_trimmed" = "$got" ]; then
      return 0
    fi

    # Extract hash and filename parts
    # First field is the hash, rest is filename (which may contain spaces)
    line_hash=$(echo "$line" | cut -d' ' -f1)

    # Skip if hash doesn't match
    if [ "$line_hash" != "$got" ]; then
      continue
    fi

    # Hash matches, now check filename
    # Remove the hash part from the beginning of the line
    line_rest="${line#"$got"}"
    # Remove leading spaces
    while [ "${line_rest#[ ]}" != "$line_rest" ]; do
      line_rest="${line_rest#[ ]}"
    done

    # Remove leading asterisk if present (binary mode indicator)
    if [ "${line_rest#\*}" != "$line_rest" ]; then
      line_rest="${line_rest#\*}"
    fi

    # Extract just the filename without any path
    line_filename="${line_rest##*/}"

    # Check if the filename matches
    if [ "$line_filename" = "$BASENAME" ]; then
      return 0
    fi
  done < "$SUMFILE"

  log_err "hash_verify checksum for '$TARGET_PATH' did not verify"
  log_err "  Expected hash: ${got}"
  log_err "  Checksum file content:"
  cat "$SUMFILE" >&2
  return 1
}

# GitHub HTTP download functions with GITHUB_TOKEN support
github_http_download_curl() {
  local_file=$1
  source_url=$2
  header=$3
  if [ -n "$GITHUB_TOKEN" ]; then
    log_debug "Using GITHUB_TOKEN for authentication"
    if [ -z "$header" ]; then
      curl -fsSL -H "Authorization: Bearer $GITHUB_TOKEN" -o "$local_file" "$source_url"
    else
      curl -fsSL -H "Authorization: Bearer $GITHUB_TOKEN" -H "$header" -o "$local_file" "$source_url"
    fi
  else
    if [ -z "$header" ]; then
      curl -fsSL -o "$local_file" "$source_url"
    else
      curl -fsSL -H "$header" -o "$local_file" "$source_url"
    fi
  fi
}
github_http_download_wget() {
  local_file=$1
  source_url=$2
  header=$3
  if [ -n "$GITHUB_TOKEN" ]; then
    log_debug "Using GITHUB_TOKEN for authentication"
    if [ -z "$header" ]; then
      wget -q --header "Authorization: Bearer $GITHUB_TOKEN" -O "$local_file" "$source_url"
    else
      wget -q --header "Authorization: Bearer $GITHUB_TOKEN" --header "$header" -O "$local_file" "$source_url"
    fi
  else
    if [ -z "$header" ]; then
      wget -q -O "$local_file" "$source_url"
    else
      wget -q --header "$header" -O "$local_file" "$source_url"
    fi
  fi
}
github_http_download() {
  log_debug "github_http_download $2"
  if is_command curl; then
    github_http_download_curl "$@"
    return
  elif is_command wget; then
    github_http_download_wget "$@"
    return
  fi
  log_crit "github_http_download unable to find wget or curl"
  return 1
}
github_http_copy() {
  tmp=$(mktemp)
  github_http_download "${tmp}" "$@" || return 1
  body=$(cat "$tmp")
  rm -f "${tmp}"
  echo "$body"
}
github_release() {
  owner_repo=$1
  version=$2
  test -z "$version" && version="latest"
  giturl="https://github.com/${owner_repo}/releases/${version}"
  json=$(github_http_copy "$giturl" "Accept:application/json")
  test -z "$json" && return 1
  version=$(echo "$json" | tr -s '\n' ' ' | sed 's/.*"tag_name":"//' | sed 's/".*//')
  test -z "$version" && return 1
  echo "$version"
}

# --- Embedded Checksums (Format: VERSION:FILENAME:HASH) ---
EMBEDDED_CHECKSUMS="
3.46.4:task_darwin_amd64.tar.gz:6e3d1bf5fcc03e50b2c02c92335923b715d3f61e27fef5b3048b59ed97a18721
3.46.4:task_darwin_arm64.tar.gz:ffe2b4a3c54467172ab15734d0b451b1fc0472d0d48bb3538870b433c700bc96
3.46.4:task_freebsd_386.tar.gz:37efbab3e10723fbba85114ffb5cd39938ed489b69674e15605ec96989c047b5
3.46.4:task_freebsd_amd64.tar.gz:cd0be727b17943a53004c9984526649010aa7710cd4fac4a84b805ae25f1f35c
3.46.4:task_freebsd_arm.tar.gz:f267218e5ae49f7bbbe41c94377b3c0694c79411b9180fccc21b43cc8ef45284
3.46.4:task_freebsd_arm64.tar.gz:e68251346bc140f367f42a34fdc327edb63612a66bd782cd713a1c812531a13c
3.46.4:task_linux_386.tar.gz:b0e93c6290ed91af882516117114999ff0b21ac08d8c4e7e6f63ed6a12ef95b5
3.46.4:task_linux_amd64.tar.gz:4b0098862292de03d568c851b207bce5fdb8a59cb533d6ed4132386151926c46
3.46.4:task_linux_arm.tar.gz:f08d96178a6612e6c548e103c022740c82a313d04f7f90421d7550356ac8ee02
3.46.4:task_linux_arm64.tar.gz:9079bbdfd439f2168ee380d9167fd77f13f9fab7afb516205ac3a578f16bcb59
3.46.4:task_linux_riscv64.tar.gz:c05fb7d47c0c5d1b8222362bf2edaae6cbe6d33c3b38f0ec034306425ee51761
3.46.4:task_windows_386.zip:1398d3b96f5b7dfb71b2a126dbb5849369da130099783ebd899a162ff091f6a3
3.46.4:task_windows_amd64.zip:790420c11a6457a27f135c292371d6a352436dfce7dba5b5ffa8ae399ecfe04b
3.46.4:task_windows_arm.zip:450bf906119ddf741e99c44569329b9493c4b6f55f4c3d736297b3d57826fb32
3.46.4:task_windows_arm64.zip:4ef119dfc6ed5133170f6fc20085f0602701a37c90b440ee54331b6370f2914d
3.49.1:task_darwin_amd64.tar.gz:8bc4dd3baed1c71956ade0bb0a9c1b94e3ed7b65e7f2ff3aab13d0562c820e59
3.49.1:task_darwin_arm64.tar.gz:0f556b66df69d53b790c7fd26bfab73543b4a5ce1767df6b2e8499619e2a205b
3.49.1:task_freebsd_386.tar.gz:138252389b4ccf42f3091d62e9908ed79febd43b7950cb7bc69ac5d5763780f8
3.49.1:task_freebsd_amd64.tar.gz:faada0d291ba37c7d57d847055b8d997f42ebd1b393fb05d60af288a6e2c59a5
3.49.1:task_freebsd_arm.tar.gz:c98b6a6298eac77701d2a3a0f312a5c9081ea86b6488615261328371a2b27778
3.49.1:task_freebsd_arm64.tar.gz:39fb5c455af82c2a7f876ec7488f9f92916efae4453399359bfdd2f1207269ec
3.49.1:task_linux_386.tar.gz:ed3aa9772dcbcef6ec3cbd3690884eae3398b15db470b3d267f4f935ce27389c
3.49.1:task_linux_amd64.tar.gz:4e7d24f1bf38218aec8f244eb7ba671f898830f9f87b3c9b30ff1c09e3135576
3.49.1:task_linux_arm.tar.gz:364b6dba58ec2825b4f6ebb24004bbe1097dbc1c88199bfa19bb309aa6cfc1e5
3.49.1:task_linux_arm64.tar.gz:aa6732c9c66397c5380ec2b60c070fd599075b2a8538dba03f3a21edc99ab0cb
3.49.1:task_linux_riscv64.tar.gz:ca3269ca1d7dde2b938542581a352e82e9e71a6e0bac18eb215960a2664d570e
3.49.1:task_windows_386.zip:8214f97c6b16223083c1486e0611df9274717c7d0a3b36c1f2370cbfa8cb268e
3.49.1:task_windows_amd64.zip:725c551f699d4d6c0dc57bd8148f72bef8d5b2fb650d9c985f271a61522fd521
3.49.1:task_windows_arm64.zip:bacbc74ee6a1402179b62966f3e3f5b9047b6a6c2688c4ad3c08946b5a4cf731
3.50.0:task_darwin_amd64.tar.gz:da3ba003ec049fb8be1ff798132c951dcd08a60efbdc2d1e918bf2095cd4a39c
3.50.0:task_darwin_arm64.tar.gz:838b7954f227b5e8f798ad83111195aed810cf4f98dfabef4aa77ea065dd74b0
3.50.0:task_freebsd_386.tar.gz:706b4a64faf8a607e186362638dbc29f868dc27dce661399d8ccc864dd5dac34
3.50.0:task_freebsd_amd64.tar.gz:eef4691c6a50a20477a780342b96e9ec59f7b678bcb394b40e5d9c909d7655d2
3.50.0:task_freebsd_arm.tar.gz:f454ae8f9334a02dde80c2bc9105f4c1965a7d8f6328cd76c94d1a214574e5ad
3.50.0:task_freebsd_arm64.tar.gz:7c82d69b6af740b65b996423470fdecbd92f76829741b0a7712b8d65a4e764fe
3.50.0:task_linux_386.tar.gz:e3537d3bc1a52ca6af4e88b835f6dbb4fabeb6134b6c7b0be462f7076462c0a8
3.50.0:task_linux_amd64.tar.gz:d449ba85ab85a0769989d78f8b9872938e4ba9347f7f4f925f73d98272a0a655
3.50.0:task_linux_arm.tar.gz:c8c54a231ba8881720687e04fbe59cb6962379b9b0c5962aedf16e9cde6bdf21
3.50.0:task_linux_arm64.tar.gz:ee67e7d999a4a70711bff1946c70bf76628012c91d9be55626ee90ba976897da
3.50.0:task_linux_riscv64.tar.gz:cedb6c70b046953c50c54466e0535cbc4f89183878a35e7edb0248d0b04123ea
3.50.0:task_windows_386.zip:b2e3017bd47e95f9801379f978e44f3cf747696eca0124e7b6bb58702eb5a330
3.50.0:task_windows_amd64.zip:82c20fbd19ac62073b8ecf89e026fbd209f702a2922106e4ff2ed6934d193038
3.50.0:task_windows_arm64.zip:e41ecc600429b9673ecdb45d35f04d96b4f148d83d3d1af496b8177f86ef8d83"

# Find embedded checksum for a given version and filename
find_embedded_checksum() {
  version="$1"
  filename="$2"
  echo "$EMBEDDED_CHECKSUMS" | grep -E "^${version}:${filename}:" | cut -d':' -f3
}
parse_args() {
  BINDIR="${BINSTALLER_BIN:-${HOME}/.local/bin}"
  DRY_RUN=0
  while getopts "b:dqh?xn" arg; do
    case "$arg" in
    b) BINDIR="$OPTARG" ;;
    d) log_set_priority 10 ;;
    q) log_set_priority 3 ;;
    h | \?) usage "$0" ;;
    x) set -x ;;
    n) DRY_RUN=1 ;;
    esac
  done
  shift $((OPTIND - 1))
  TAG="${1:-v3.50.0}"
}
tag_to_version() {
  if [ "$TAG" = "latest" ]; then
    log_info "checking GitHub for latest tag"
    REALTAG=$(github_release "${REPO}" "${TAG}") && true
    test -n "$REALTAG" || {
      log_crit "Could not determine latest tag for ${REPO}"
      exit 1
    }
  else
    # Assume TAG is a valid tag/version string
    REALTAG="$TAG"
  fi
  if test -z "$REALTAG"; then
    log_crit "unable to find '${TAG}' - use 'latest' or see https://github.com/${REPO}/releases for details"
    exit 1
  fi
  VERSION=${REALTAG#v} # Strip leading 'v'
  TAG="$REALTAG"       # Use the resolved tag
  log_info "Resolved version: ${VERSION} (tag: ${TAG})"
}



resolve_asset_filename() {

  # --- Apply Rules ---
  ASSET_FILENAME=""
  if [ "${UNAME_OS}" = 'windows' ] && true
  then
    EXT='.zip'
  fi
  if [ -z "${ASSET_FILENAME}" ]; then
    ASSET_FILENAME="task_${OS}_${ARCH}${EXT}"
  fi
}
# Cleanup function to remove temporary files and stop progress
cleanup() {
  # Stop progress animation
  progress_clear

  if [ -n "$TMPDIR" ] && [ -d "$TMPDIR" ]; then
    log_debug "Cleaning up temporary directory: $TMPDIR"
    rm -rf -- "$TMPDIR"
  fi
}

execute() {
  STRIP_COMPONENTS=0
  CHECKSUM_FILENAME="task_checksums.txt"

  # --- Construct URLs ---
  GITHUB_DOWNLOAD="https://github.com/${REPO}/releases/download"
  ASSET_URL="${GITHUB_DOWNLOAD}/${TAG}/${ASSET_FILENAME}"
  CHECKSUM_URL=""
  if [ -n "$CHECKSUM_FILENAME" ]; then
    CHECKSUM_URL="${GITHUB_DOWNLOAD}/${TAG}/${CHECKSUM_FILENAME}"
  fi

  # --- Download and Verify ---
  TMPDIR=$(mktemp -d)
  # Set up cleanup trap that includes progress clearing
  trap cleanup EXIT HUP INT TERM
  log_debug "Downloading files into ${TMPDIR}"
  log_info "Downloading ${ASSET_URL}"
  github_http_download "${TMPDIR}/${ASSET_FILENAME}" "${ASSET_URL}"

  # Try to find embedded checksum first
  EMBEDDED_HASH=$(find_embedded_checksum "$VERSION" "$ASSET_FILENAME")

  if [ -n "$EMBEDDED_HASH" ]; then
    log_info "Using embedded checksum for verification"

    # Verify using embedded hash
    got=$(hash_compute "${TMPDIR}/${ASSET_FILENAME}")
    if [ "$got" != "$EMBEDDED_HASH" ]; then
      log_crit "Checksum verification failed for ${ASSET_FILENAME}"
      log_crit "Expected: ${EMBEDDED_HASH}"
      log_crit "Got: ${got}"
      return 1
    fi
    log_info "Checksum verification successful"
  elif [ -n "$CHECKSUM_URL" ]; then
    # Fall back to downloading checksum file
    log_info "Downloading checksums from ${CHECKSUM_URL}"
    github_http_download "${TMPDIR}/${CHECKSUM_FILENAME}" "${CHECKSUM_URL}"
    log_info "Verifying checksum ..."
    hash_verify "${TMPDIR}/${ASSET_FILENAME}" "${TMPDIR}/${CHECKSUM_FILENAME}"
  else
    log_info "No checksum found, skipping verification."
  fi

  if [ -z "${EXT}" ] || [ "${EXT}" = ".exe" ]; then
    log_debug "Target is raw binary"
  else
    log_info "Extracting ${ASSET_FILENAME}..."
    (cd "${TMPDIR}" && untar "${ASSET_FILENAME}" "${STRIP_COMPONENTS}")
  fi
  BINARY_NAME='task'
  if [ -z "${EXT}" ] || [ "${EXT}" = ".exe" ]; then
    BINARY_PATH="${TMPDIR}/${ASSET_FILENAME}"
  else
    BINARY_PATH="${TMPDIR}/task"
  fi

  if [ "${UNAME_OS}" = "windows" ]; then
    case "${BINARY_NAME}" in *.exe) ;; *) BINARY_NAME="${BINARY_NAME}.exe" ;; esac
    case "${BINARY_PATH}" in *.exe) ;; *) BINARY_PATH="${BINARY_PATH}.exe" ;; esac
  fi

  if [ ! -f "${BINARY_PATH}" ]; then
    log_crit "Binary not found: ${BINARY_PATH}"
    log_crit "Listing contents of ${TMPDIR} ..."
    if command -v find >/dev/null 2>&1; then
      cd "${TMPDIR}" && find .
    else
      cd "${TMPDIR}" && ls -R .
    fi
    return 1
  fi

  progress_clear
  # Install the binary
  INSTALL_PATH="${BINDIR}/${BINARY_NAME}"

  if [ "$DRY_RUN" = "1" ]; then
    log_info "[DRY RUN] ${BINARY_NAME} dry-run installation succeeded! (Would install to: ${INSTALL_PATH})"
  else
    log_info "Installing binary to ${INSTALL_PATH}"
    test ! -d "${BINDIR}" && install -d "${BINDIR}"
    install "${BINARY_PATH}" "${INSTALL_PATH}"
    log_info "${BINARY_NAME} installation complete!"
  fi
}

# --- Configuration  ---
NAME='task'
REPO='go-task/task'
EXT='.tar.gz'

# use in logging routines
log_prefix() {
  echo "${REPO}"
}

parse_args "$@"

progress_init
progress_pulse_start

# --- Determine target platform ---
OS="${BINSTALLER_OS:-$(uname_os)}"
UNAME_OS="${OS}"

ARCH="${BINSTALLER_ARCH:-$(uname_arch)}"

log_info "Detected Platform: ${OS}/${ARCH}"

# --- Validate platform ---
uname_os_check "$OS"
uname_arch_check "$ARCH"

tag_to_version

resolve_asset_filename
execute
